
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-provisioner
  namespace: webns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: efs-provisioner
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      serviceAccountName: efs-provisioner
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:v2.5.0
          env:
            - name: FILE_SYSTEM_ID
              value: fs-05df3d088db25bd43
            - name: AWS_REGION
              value: us-east-1
          volumeMounts:
            - name: pv-volume
              mountPath : /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-05df3d088db25bd43.efs.us-east-1.amazonaws.com
            path: /